version: "3.9"

services:
  flambe-be-refactor:
    container_name: flambe-be-refactor
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "1337:1337"
